### ISSUE TITLE
Api not fetching candles

### ISSUE THREAD

**Issue by JafferWilson** [n1nj4z33/iqoptionapi#101]
Please let me know why the candles are not getting accessed. I tried and waited for the time sleep, still the `data `variable is empty.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson
How about try my fork version
https://github.com/Lu-Yi-Hsun/iqoptionapi

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  Thank you friend. Just a tiny doubt. May I know whether I can get the real time values of the candles using your API? I am quite interested in getting the realtime and the historic dataset. Historic, I can get it, but the realtime is a difficulty. May I know whether it is possible or not?
