### ISSUE TITLE
Buy does not work

### ISSUE THREAD

**Issue by AllenUchiha** [n1nj4z33/iqoptionapi#16]
It seems like the buy API doesn't work for me. Is anyone having the same issue? Is the problem currently being fixed?

**Comment by frxncisjoseph** [comment]
No, I'm having the same issue.

I'm not sure what the problem is but I am going to investigate tonight, possibly due to IQ Option updating their handling of WS? Who knows.

**Comment by Olascoaga** [comment]
https://github.com/n1nj4z33/iqoptionapi/issues/2#issuecomment-269313182

**Comment by AllenUchiha** [comment]
@Olascoaga I tried to replace this part

>    def expiration_timestamp(self):
        """Property to get expiration timestamp.
        :returns: The expiration timestamp.
        """
        #return time.mktime(self.expiration_datetime.timetuple())
        return time.mktime(self.expiration_datetime.replace(second=0, microsecond=0).timetuple())

but it still doesn't buy the options as I instructed it to.

**Comment by frxncisjoseph** [comment]
How did you manage to fix this issue? Please share with us.

**Comment by AllenUchiha** [comment]
@frxncisjoseph it is as @Olascoaga directed me to. Replace the expiration_timestamp last line and it should work.

**Comment by frxncisjoseph** [comment]
Working 100%, just as a note - if you're not running Python via a terminal and instead via an IDE then make sure that your application is kept alive. You can commonly do this via a while statement.

**Comment by tjlabais** [comment]
still works as of today?
