### ISSUE TITLE
Connection is already closed

### ISSUE THREAD

**Issue by m10141** [n1nj4z33/iqoptionapi#51]
I got error message
"  File "C:\Python27\lib\site-packages\websocket\_app.py", line 120, in send
    "Connection is already closed.")
WebSocketConnectionClosedException: Connection is already closed."
how to fix it?

**Comment by vinydl** [comment]
check proxy or internet speed

**Comment by m10141** [comment]
The internet speed is ok
I also got this message :
"hostname 'iqoption.com' doesn't match 'admin-new.affiliate.iqoption.com'"

**Comment by simschmid** [comment]
I get the same error on my first machine. My second machine connects without error.

**Comment by m10141** [comment]
I just upgrade my python version from 2.7.2 to 2.7.14.
The problem was solved.
