### ISSUE TITLE
How to buy a 'binary' option?

### ISSUE THREAD

**Issue by milteven12** [n1nj4z33/iqoptionapi#59]
Hello guys, the buy code just allows us to buy a turbo option (short expiration). 
Does anyone know how to buy a binary option? (15min expiration or more)

**Comment by lucianopinheiro** [comment]
Today, with this API, you can not.
You have to check ws messages on chrome* while navigating to see the correct syntax of websocket message.
So you can create your function. And you have to do a threshold on buy time.

It is not so difficult. The tricky part is to retrieve the available times from iqoption for each active.

* F12, Network, WS

**Comment by milteven12** [comment]
Hello @lucianopinheiro , so, I made a call in EURUSD-OTC with $1.20, WS stays blank all the time but the XHR gets a event:

![iq-binary-order](https://user-images.githubusercontent.com/25005998/31566955-66ea5fe0-b043-11e7-9d0e-0493e68a0c31.PNG)
By IQ Option interface:
the order was made in: 13 Out 18:17:31
expiration: 13 Out 18:30:00

To compare to a 'turbo / short expiration' I made a put at the same pair with same value: (WS stills blank)
![iq-turbo-put](https://user-images.githubusercontent.com/25005998/31567099-2d9cf1f2-b044-11e7-869b-5f3e0b975377.PNG)

@ Just a uncommon thing:
If you analise the turbo option, the diference between expiration time and server time is 70 seconds IF you round the server time to the same number quantity than the expiration time, but why the 10 seconds more?

**Comment by milteven12** [comment]
Hello @lucianopinheiro  , thanks for the answer, I will work on it.
Do you know how to swap between demo and real account?

**Comment by lucianopinheiro** [comment]
You need first to know your account numbers (there is one for the real and another for the demo mode). You have to use chrome devtools again. I think the function (and ws command) is changebalance `(./http/changebalance.py)`. I don't remember... You will see in devtools.

**Comment by martppa** [comment]
Hello Guys, I see this is the most recent post. Does anyone of you know the IQoption API address? I can't find it.

**Comment by milteven12** [comment]
@martppa , sorry man, I don't know.

@lucianopinheiro , thank your for your help, now I can switch between demo and real. About the binary option, I'm trying the Websocket thing but the chrome stays blank all the time, do you know what I can be doing wrong?

**Comment by lucianopinheiro** [comment]
I just know about ws message `api_option_init_all`, but I could not get it. I don't know why. On website, it gets at start of the session. It is part of the starting config of everything. I don't know how we get the updates, neither if it is possible. If you get the variable, please post here the solution.

**Comment by keinbuck** [comment]
To buy a binary option you must call `api.buy(1,1,"binary","call")`
Furthermore you have to update expiration_timestamp in timesync.py or in buyv2.py to the next 15 minute intervall. For me it works perfect.

**Comment by martppa** [comment]
@milteven12 Thanks for your answer. Anyway I think you don't my question. This API written in python uses some kind of http address to connect to the IQoption server. I did search in the whole code and couldn't find it. So it is not hardcoded. You have to introduce the address in order to work. Could any one of you tell me which one are you using? I am sorry if I am going out of topic.

**Comment by lucianopinheiro** [comment]
Please, open another issue
